/**
 * @file GameLoop.ixx
 * @brief Central orchestrator for the game update cycle.
 */
module;

#include <cassert>
#include <memory>
#include <vector>
#include <span>

export module helios.engine.runtime.gameloop:GameLoop;

import helios.engine.runtime.world.GameWorld;

import helios.engine.runtime.world.UpdateContext;
import helios.core.log.Logger;
import helios.core.log.LogManager;

import helios.ecs;

import helios.engine.runtime.enginestate.types;

import :Pass;
import :Phase;

import helios.ecs.Manager;

import helios.engine.input.InputSnapshot;

import helios.engine.runtime.world.GameWorld;

using namespace helios::engine::runtime::world;

#define HELIOS_LOG_SCOPE "helios::engine::runtime::gameloop::GameLoop"
export namespace helios::engine::runtime::gameloop {

    /**
     * @brief Central orchestrator for the game update cycle.
     *
     *
     * ## Ownership
     *
     * The GameLoop owns:
     * - **Three phases** (Pre, Main, Post), each containing passes with registered systems.
     * - **Three event buses** for different propagation scopes:
     *   - `phaseEventBus_`: Events readable in the next phase.
     *   - `passEventBus_`: Events readable in subsequent passes (within the same phase).
     *   - `frameEventBus_`: Events readable in the next frame.
     *
     *
     * @see Phase
     * @see Pass
     * @see ResourceRegistry
     * @see EngineCommandBuffer
     * @see PassEndListener
     */
    template<typename TTypedHandleWorld>
    class GameLoop {


        /**
         * @brief Flag indicating whether init() has been called.
         *
         * Used to assert that init() is called exactly once before the first update()
         * and to prevent multiple initializations.
         */
        bool initialized_ = false;
    protected:



        /**
         * @brief The logger used with this GameLoop instance.
         */
        inline static const helios::core::log::Logger& logger_ = helios::core::log::LogManager::loggerForScope(
            HELIOS_LOG_SCOPE);
        GameWorld<TTypedHandleWorld>& gameWorld_;


        /**
         * @brief The pre-update phase, executed before main gameplay logic.
         */
        helios::engine::runtime::gameloop::Phase<TTypedHandleWorld> prePhase_;

        /**
         * @brief The main update phase for core gameplay systems.
         */
        helios::engine::runtime::gameloop::Phase<TTypedHandleWorld> mainPhase_;

        /**
         * @brief The post-update phase for cleanup and synchronization.
         */
        helios::engine::runtime::gameloop::Phase<TTypedHandleWorld> postPhase_;

        /**
         * @brief Accumulated total time since the first frame, in seconds.
         */
        float totalTime_ = 0.0f;

        /**
         * @brief The current frame count for this GameLoop.
         */
        std::size_t frameCount_ = 0;

        /**
         * @brief Commits phase-level events and flushes commands and managers.
         *
         * Called after each phase completes. This method:
         *
         * 1. Clears pass event buffers for the new phase.
         * 2. Flushes the command buffer, executing deferred commands.
         * 3. Flushes managers, allowing to process any request generated by the commands.
         * 4. Swaps phase event bus buffers, making events readable in the next phase.

         * @param gameWorld Reference to the game world.
         * @param updateContext The current update context.
         *
         * @see UpdateContext::pushPhase()
         * @see UpdateContext::readPhase()
         */
        void phaseEnd(
            GameWorld<TTypedHandleWorld>& gameWorld,
            runtime::world::UpdateContext& updateContext) {

        }


    public:


        /**
         * @brief Constructs a GameLoop bound to a GameWorld.
         *
         * @details Initializes all phases with the same `GameWorld` reference
         * so passes can resolve world-owned resources (for example command
         * buffers) during system registration.
         *
         * @param gameWorld The GameWorld associated with this GameLoop.
         */
        GameLoop(GameWorld<TTypedHandleWorld>& gameWorld) : gameWorld_(gameWorld), prePhase_(*this, gameWorld_), mainPhase_(*this, gameWorld_), postPhase_(*this, gameWorld_) {};


        /**
         * @brief Returns a reference to the specified phase.
         *
         * @param phaseType The type of phase to retrieve (Pre, Main, or Post).
         *
         * @return Reference to the requested Phase.
         */
        [[nodiscard]] helios::engine::runtime::gameloop::Phase<TTypedHandleWorld>& phase(const helios::engine::runtime::gameloop::PhaseType phaseType) noexcept {

            switch (phaseType) {
                case helios::engine::runtime::gameloop::PhaseType::Pre:
                    return prePhase_;
                    break;
                case helios::engine::runtime::gameloop::PhaseType::Main:
                    return mainPhase_;
                    break;
                case helios::engine::runtime::gameloop::PhaseType::Post:
                    return postPhase_;
                    break;
            }

            std::unreachable();

        }


        /**
         * @brief Initializes the GameLoop and all registered phases and passes.
         *
         * @details Iterates through all phases (Pre, Main, Post) and calls their
         * `init()` methods, which in turn initialize all registered passes and
         * systems. Systems receive a reference to the GameWorld for component
         * queries and entity access.
         *
         * Must be called exactly once before the first `update()` call.
         *
         * @param gameWorld Reference to the game world to initialize with.
         *
         * @pre Must not have been called before (asserts on multiple calls).
         *
         * @see Phase::init()
         * @see Pass::init()
         * @see System::init()
         */
        void init(GameWorld<TTypedHandleWorld>& gameWorld) {

            assert(!initialized_ && "init() already called");

            prePhase_.init(gameWorld);

            mainPhase_.init(gameWorld);

            postPhase_.init(gameWorld);

            initialized_ = true;
        }

        GameWorld<TTypedHandleWorld>& gameWorld() noexcept {
            return gameWorld_;
        }

        /**
         * @brief Executes one full frame update across all phases.
         *
         * @param gameWorld Reference to the game world.
         * @param deltaTime Time elapsed since the last frame in seconds.
         * @param inputSnapshot Snapshot of the current input state.
         *
         * @pre init() must have been called before the first update.
         *
         * @see Phase
         * @see phaseEnd()
         * @see UpdateContext
         */
        void update(
            GameWorld<TTypedHandleWorld>& gameWorld,
            float deltaTime,
            const helios::engine::input::InputSnapshot& inputSnapshot
        ) noexcept {

            assert(initialized_ && "GameLoop not initialized");

            totalTime_ += deltaTime;
            frameCount_++;

            auto updateContext = runtime::world::UpdateContext(
                  gameWorld.session(),
                  gameWorld.runtimeEnvironment(),
                  deltaTime,
                  totalTime_,
                  frameCount_,
                  inputSnapshot,
                  gameWorld.level(),
                  gameWorld.engineWorld()
              );

            auto& session = gameWorld.session();

            // gameloop phases
            prePhase_.update(gameWorld, updateContext);
            phaseEnd(gameWorld, updateContext);

            mainPhase_.update(gameWorld, updateContext);
            phaseEnd(gameWorld, updateContext);

            postPhase_.update(gameWorld, updateContext);
            phaseEnd(gameWorld, updateContext);
        }


        [[nodiscard]] bool isRunning(GameWorld<TTypedHandleWorld>& gameWorld) const noexcept {
            return initialized_ && !gameWorld.session().isDestroyed();
        }



    };

}

