#ifndef NDEBUG
    #define HELIOS_DEBUG 1
#endif

#if defined(_MSC_VER)
    #define HELIOS_FUNCTION_SIGNATURE __FUNCSIG__
#elif defined(__clang__) || defined(__GNUC__)
    #define HELIOS_FUNCTION_SIGNATURE __PRETTY_FUNCTION__
#else
    #define HELIOS_FUNCTION_SIGNATURE __func__
#endif

#define ENTITY_MANAGER_DEFAULT_CAPACITY 1000

#define UI_ACTION_COMMAND_HANDLER_DEFAULT_CAPACITY 100

#define STATE_TO_IDMAP_DEFAULT_CAPACITY 20

#define INACTIVE_FOCUSED_ITEMS_CACHE_CAPACITY 20

#define DEFAULT_ENTITY_MANAGER_CAPACITY 1000

#define DEFAULT_GAMEOBJECT_CAPACITY 1000

#define DEFAULT_GAMEOBJECT_POOL_CAPACITY 1000
#define DEFAULT_WINDOW_POOL_CAPACITY 5
#define DEFAULT_SHADER_POOL_CAPACITY 100
#define DEFAULT_MESH_POOL_CAPACITY 100
#define DEFAULT_MATERIAL_POOL_CAPACITY 100
#define DEFAULT_VIEWPORT_POOL_CAPACITY 10
#define DEFAULT_FRAMEBUFFER_POOL_CAPACITY 10
#define DEFAULT_SCENE_POOL_CAPACITY 10

#define HELIOS_DEFAULT_VISIBLE_MEMBER_CAPACITY 1000

#define DEFAULT_INSTANCE_RENDER_BATCH_CAPACITY 100
#define DEFAULT_INSTANCE_DATA_CAPACITY 1000

#define DEFAULT_ENTITY_MUTATION_COMMAND_BUFFER_CAPACITY 1000

#define DEFAULT_RUNTIME_HANDLE_REGISTRY_CAPACITY 50