#ifndef NDEBUG
    #define HELIOS_DEBUG 1
#endif

#if defined(_MSC_VER)
    #define HELIOS_FUNCTION_SIGNATURE __FUNCSIG__
#elif defined(__clang__) || defined(__GNUC__)
    #define HELIOS_FUNCTION_SIGNATURE __PRETTY_FUNCTION__
#else
    #define HELIOS_FUNCTION_SIGNATURE __func__
#endif

#define ENTITY_MANAGER_DEFAULT_CAPACITY 1000

#define UI_ACTION_COMMAND_HANDLER_DEFAULT_CAPACITY 100

#define STATE_TO_IDMAP_DEFAULT_CAPACITY 20

#define INACTIVE_FOCUSED_ITEMS_CACHE_CAPACITY 20


// +--------------------------------------------------
// | Default capacities for various entity managers
// +--------------------------------------------------
#define GAMEOBJECT_INITIAL_STORAGE_CAPACITY 1000
#define PARTICLE_INITIAL_STORAGE_CAPACITY 1000

#define WINDOW_INITIAL_STORAGE_CAPACITY 5
#define PLATFORM_INITIAL_STORAGE_CAPACITY 1

#define SHADER_INITIAL_STORAGE_CAPACITY 100
#define MESH_INITIAL_STORAGE_CAPACITY 100
#define MATERIAL_INITIAL_STORAGE_CAPACITY 100
#define VIEWPORT_POOL_CAPACITY 10
#define TEXTURE_INITIAL_STORAGE_CAPACITY 100

// EntityManager capacities for render view related entities
#define SCENE_INITIAL_STORAGE_CAPACITY 10
#define CAMERA_INITIAL_STORAGE_CAPACITY 10
#define VIEWPORT_INITIAL_STORAGE_CAPACITY 10
#define RENDERTARGET_INITIAL_STORAGE_CAPACITY 10
//==========================================================

#define HELIOS_DEFAULT_VISIBLE_MEMBER_CAPACITY 1000

#define DEFAULT_INSTANCE_RENDER_BATCH_CAPACITY 100
#define DEFAULT_INSTANCE_DATA_CAPACITY 1000

#define DEFAULT_ENTITY_MUTATION_COMMAND_BUFFER_CAPACITY 1000

#define DEFAULT_RUNTIME_HANDLE_REGISTRY_CAPACITY 50

// The capacity for handle-specific collections of pools in TypedEntityPoolRegistry.
#define DEFAULT_TYPEDENTITYPOOL_CAPACITY 50